name: CI

permissions:
  contents: write

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.2

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4.1.0

      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
          distribution: adopt

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4.1.0

      - name: Build app
        run: 
          ./gradlew spotlessApply spotlessCheck assembleStandardRelease assembleStandardPreview
          
      - name: Upload APK
        uses: actions/upload-artifact@v4.4.3
        with:
          name: arm64-v8a-${{ github.sha }}
          path: app/build/outputs/apk/standard/release/app-standard-arm64-v8a-release-unsigned.apk

      - name: Upload Preview APK
        uses: actions/upload-artifact@v4.4.3
        with:
          name: arm64-v8a-preview-${{ github.sha }}
          path: app/build/outputs/apk/standard/preview/app-standard-arm64-v8a-preview.apk

      - name: Upload mapping
        uses: actions/upload-artifact@v4.4.3
        with:
          name: mapping-${{ github.sha }}
          path: app/build/outputs/mapping/standardRelease

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Clean up build artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -e

          mv app/build/outputs/apk/standard/release/app-standard-universal-release-unsigned.apk aniyomi-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum aniyomi-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-arm64-v8a-release-unsigned.apk aniyomi-arm64-v8a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum aniyomi-arm64-v8a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/preview/app-standard-arm64-v8a-preview-unsigned.apk aniyomi-arm64-v8a-preview-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum aniyomi-arm64-v8a-preview-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_PREVIEW_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-armeabi-v7a-release-unsigned.apk aniyomi-armeabi-v7a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum aniyomi-armeabi-v7a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-x86-release-unsigned.apk aniyomi-x86-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum aniyomi-x86-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-x86_64-release-unsigned.apk aniyomi-x86_64-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum aniyomi-x86_64-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_64_SHA=$sha" >> $GITHUB_ENV

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2.0.8
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Aniyomi ${{ env.VERSION_TAG }}
          body: |
            ---

            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal | ${{ env.APK_UNIVERSAL_SHA }} |
            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }} |
            | arm64-v8a (Preview) | ${{ env.APK_ARM64_V8A_PREVIEW_SHA }} |
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }} |
            | x86 | ${{ env.APK_X86_SHA }} |
            | x86_64 | ${{ env.APK_X86_64_SHA }} |
          files: |
            aniyomi-${{ env.VERSION_TAG }}.apk
            aniyomi-arm64-v8a-${{ env.VERSION_TAG }}.apk
            aniyomi-arm64-v8a-preview-${{ env.VERSION_TAG }}.apk
            aniyomi-armeabi-v7a-${{ env.VERSION_TAG }}.apk
            aniyomi-x86-${{ env.VERSION_TAG }}.apk
            aniyomi-x86_64-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}